---------------------------------
-- Markus Dwiyanto Tobi Sogen
-- CS50 for teachers
-- Indonesia
-- query to list the titles and release years of all Harry Potter movies, in chronological order
----------------------------------